# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14459f89c01a0d6acaf2f889b8c1ca4f06bbffe2b1d68dd01e5e4edd427788a259ce02b9eaac49fe2d55ed04d4f95a69251c053916a4bf31c11b5e0bea74d9db

test:
  secret_key_base: eec448ef31a1de3d1faaee10d45f1eb4fcb1ac9a0249f4cec75b1a1d311c7dcfe1a44af8010fdd724e55be20e4cbd4231da606ca3442913687c31b4179f31ee8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
